PG_MAJOR?=11
PGVERSION=pg$(PG_MAJOR)
POSTGIS_VERSIONS?="2.5 3"

# CI/CD can benefit from specifying a specific apt packages mirror
DEBIAN_REPO_MIRROR?=""

# These variables have to do with this Docker repository
GIT_COMMIT=$(shell git describe --always --tag --long --abbrev=8)
GIT_BRANCH=$(shell git symbolic-ref --short HEAD)
GIT_REMOTE=$(shell git config --get remote.origin.url | sed 's/.*@//g')
GIT_STATUS=$(shell git status --porcelain | paste -sd "," -)
GIT_AUTHOR?=$(USER)
GIT_REV?=$(shell git rev-parse HEAD)

# These variables have to do with what software we pull in from github
GITHUB_USER?=""
GITHUB_TOKEN?=""
GITHUB_REPO?="timescale/timescaledb"
GITHUB_TAG?="master"

TAG?=$(subst /,_,$(GIT_BRANCH)-$(GIT_COMMIT))
REGISTRY?=localhost:5000
TIMESCALEDB_REPOSITORY?=timescale/timescaledb-docker-ha
TIMESCALEDB_IMAGE?=$(REGISTRY)/$(TIMESCALEDB_REPOSITORY)
TIMESCALEDB_BUILDER_URL?=$(TIMESCALEDB_IMAGE):builder-$(PGVERSION)
TIMESCALEDB_RELEASE_URL?=$(TIMESCALEDB_IMAGE):$(TAG)-$(PGVERSION)
TIMESCALEDB_LATEST_URL?=$(TIMESCALEDB_IMAGE):latest-$(PGVERSION)
PG_PROMETHEUS?=0.2.2
INSTALL_METHOD?="docker-ha"

CICD_REPOSITORY=registry.gitlab.com/timescale/timescaledb-docker-ha
DOCKER_HUB_REPOSITORY=localhost:32000/timescaledev/timescaledb-ha

# We label all the Docker Images with the versions of PostgreSQL, TimescaleDB and other extensions
# that are in versions.json.
# versions.json is generated by starting a builder container and querying the PostgreSQL catalogs
# for all the version information. In that way, we are sure we never tag the Docker images with the wrong
# versions.
# I'm using $$(jq) instead of $(shell), as we need to evaluate these variables for every new image build
DOCKER_BUILD_COMMAND=docker build --build-arg PG_MAJOR=$(PG_MAJOR) \
					 --build-arg INSTALL_METHOD="$(INSTALL_METHOD)" \
					 --build-arg PG_PROMETHEUS=$(PG_PROMETHEUS) \
					 --build-arg DEBIAN_REPO_MIRROR=$(DEBIAN_REPO_MIRROR) $(DOCKER_IMAGE_CACHE) \
					 --label org.opencontainers.image.created="$$(date -Iseconds --utc)" \
					 --label org.opencontainers.image.revision="$(GIT_REV)" \
					 --label org.opencontainers.image.vendor=Timescale \
					 --label org.opencontainers.image.source="$(GIT_REMOTE)" \
					 $$(jq 'to_entries | map("--label com.timescaledb.image.\(.key).version=\(.value)") | join(" ")' -r versions.json)

default: build

.build_$(TAG)_$(PGVERSION)_postgis: Dockerfile versions.json
	$(DOCKER_BUILD_COMMAND) -t $(TIMESCALEDB_RELEASE_URL)-postgis --build-arg POSTGIS_VERSIONS=$(POSTGIS_VERSIONS) .
	docker tag $(TIMESCALEDB_RELEASE_URL)-postgis $(TIMESCALEDB_LATEST_URL)-postgis
	touch .build_$(TAG)_$(PGVERSION)_postgis

.build_$(TAG)_$(PGVERSION)_oss: Dockerfile versions.json
	$(DOCKER_BUILD_COMMAND) -t $(TIMESCALEDB_RELEASE_URL)-oss --build-arg OSS_ONLY=" -DAPACHE_ONLY=1"  .
	docker tag $(TIMESCALEDB_RELEASE_URL)-oss $(TIMESCALEDB_LATEST_URL)-oss
	touch .build_$(TAG)_$(PGVERSION)_oss

.build_$(TAG)_$(PGVERSION)_tag: Dockerfile versions.json
	$(DOCKER_BUILD_COMMAND) -t $(TIMESCALEDB_RELEASE_URL) \
		--build-arg GITHUB_REPO=$(GITHUB_REPO) --build-arg GITHUB_USER=$(GITHUB_USER) \
		--build-arg GITHUB_TOKEN=$(GITHUB_TOKEN) --build-arg GITHUB_TAG=$(GITHUB_TAG) .
	@touch .build_$(TAG)_$(PGVERSION)_tag

.build_$(TAG)_$(PGVERSION): Dockerfile versions.json
	$(DOCKER_BUILD_COMMAND) -t $(TIMESCALEDB_RELEASE_URL) .
	docker tag $(TIMESCALEDB_RELEASE_URL) $(TIMESCALEDB_LATEST_URL)
	touch .build_$(TAG)_$(PGVERSION)

versions.json: builder
	docker stop timescalebuilder || true
	docker run -d --rm --name timescalebuilder -e PGDATA=/tmp/pgdata --user=postgres $(TIMESCALEDB_BUILDER_URL) \
		sh -c 'initdb && timeout 30 postgres -D /tmp/pgdata'
	docker exec -i timescalebuilder sh -c 'while ! pg_isready; do sleep 1; done'
	cat scripts/version_info.sql | docker exec -i timescalebuilder psql -AtXq > versions.json
	docker stop timescalebuilder

builder: Dockerfile
	$(DOCKER_BUILD_COMMAND) --target builder -t $(TIMESCALEDB_BUILDER_URL) .
	touch builder

build: .build_$(TAG)_$(PGVERSION)

build-postgis: .build_$(TAG)_$(PGVERSION)_postgis

build-oss: .build_$(TAG)_$(PGVERSION)_oss

build-tag: .build_$(TAG)_$(PGVERSION)_tag
	docker image ls $(TIMESCALEDB_RELEASE_URL)

build-all: build build-oss

push-builder: builder
	docker push $(TIMESCALEDB_BUILDER_URL)

push: build
	docker push $(TIMESCALEDB_RELEASE_URL)
	docker push $(TIMESCALEDB_LATEST_URL)

push-postgis: build-postgis
	docker push $(TIMESCALEDB_RELEASE_URL)-postgis

push-oss: build-oss
	docker push $(TIMESCALEDB_RELEASE_URL)-oss

push-all: push push-postgis push-oss


.PHONY: release
release:
	@echo "This operation will push new Docker images to the timescaledev public Docker hub"                              
	@echo -n "Are you sure? [y/N] " && read ans && [ $${ans:-N} = y ]
	@echo -n "For which tagged release do you wish to push the Docker images? " && read RELEASE_TAG \
	&& for variant in "" -oss -postgis; do \
		docker pull $(CICD_REPOSITORY):$${RELEASE_TAG}-pg11$${variant} \
		&& docker run --rm $(CICD_REPOSITORY):$${RELEASE_TAG}-pg11$${variant} cat /versions.json | jq . \
		&& docker tag  $(CICD_REPOSITORY):$${RELEASE_TAG}-pg11$${variant} $(DOCKER_HUB_REPOSITORY):$${RELEASE_TAG}-pg11$${variant} \
		&& docker push $(DOCKER_HUB_REPOSITORY):$${RELEASE_TAG}-pg11$${variant}; \
	done


test: build
	# Very simple test that verifies the following things:
	# - PATH has the correct setting
	# - initdb succeeds
	# - timescaledb is correctly injected into the default configuration
	#
	# TODO: Create a good test-suite. For now, it's nice to have this target in CI/CD,
	# and have it do something worthwhile
	docker run --rm --tty $(TIMESCALEDB_RELEASE_URL) /bin/bash -c "initdb -D test && grep timescaledb test/postgresql.conf"

clean:
	rm -f *~ .build_* versions.json builder

.PHONY: default build build-postgis build-oss build-tag build-all push push-builder push-postgis push-oss push-all test
