name: Build builder and compiler image layers

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 00 * * *'

env:
  DOCKER_HUB_URL: docker.io/timescale/timescaledb-ha
  INSTALL_METHOD: docker-ha
  TIMESCALE_CLOUDUTILS: "v1.1.1"
  TIMESCALE_HOT_FORGE: "v0.1.36"
  TIMESCALE_OOM_GUARD:  "v1.1.1"
  TIMESCALE_TSDB_ADMIN: "1.0.0"
  TIMESCALEDB_TOOLKIT_EXTENSION_PREVIOUS: forge-stable-1.3.0 forge-stable-1.3.1 forge-stable-1.4.0
  TIMESCALEDB_TOOLKIT_EXTENSION: 1.5.1-cloud
  TIMESCALEDB_TOOLKIT_REPO: github.com/timescale/timescaledb-toolkit-private
  # This builder image is used to create patches in other environments.
  # Some of these patches still require PostgreSQL 12 support, therefore,
  # we include 3 versions for the builder image
  PG_VERSIONS: "14 13 12"
jobs:
  build-image:
    name: Build the builder Docker Image
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Builder Image to Docker Hub
        env:
          GIT_REV: ${{ steps.tag_name.outputs.GIT_TAG }}
          PRIVATE_REPO_TOKEN: ${{ secrets.GH_PRIVATE_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          DOCKER_PUBLISH_URLS="${DOCKER_HUB_URL}" make publish-builder
      - name: List docker Images
        env:
          GIT_REV: ${{ steps.tag_name.outputs.GIT_TAG }}
        run: |
          make list-images
